config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  get '/about', to: 'pages#about'

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  validates :text, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
   
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  before_action :authenticate_user!, only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<div id="page_wrapper">
	<h1>Editing article</h1>
	 
	<%= render 'form' %>
	 
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div id="post_content">
  <h1>Listing articles</h1>
   
  <%#= link_to 'New article', new_article_path %>

  <% @articles.each do |article| %>
    <div class="post_wrapper">
      <h2 class="title">
        <%= link_to article.title, article %>
      </h2>
      <p class="date"><%= article.created_at.strftime("%B %d, %Y") %></p>
    </div>
  <% end %>

  <!-- <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="2"></th>
    </tr>
   
    <%# @articles.each do |article| %>
      <tr>
        <td><%#= article.title %></td>
        <td><%#= article.text %></td>
        <td><%#= link_to 'Show', article_path(article) %></td>
        <td><%#= link_to 'Edit', edit_article_path(article) %></td>
        <td><%#= link_to 'Destroy', article_path(article),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </table>
   -->
</div>

app/views/articles/new.html.erb
<div id="page_wrapper">
	<h1>New Article</h1>

	<%= render 'form' %>

	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div id="post_content">
	<h1 class="title">
	  <%= @article.title %>
	</h1>

	<p class="date">
	  Submitted <%= time_ago_in_words(@article.created_at) %> Ago
	</p>

	<p class="body">
	  <%= @article.text %>
	</p>

	<div id="comments">
		<h2><%= @article.comments.count %> Comments</h2>
		<%= render @article.comments %>

		<h3>Add a comment:</h3>
		<%= render 'comments/form' %>
	</div>

	<%= link_to 'Edit', edit_article_path(@article) %> |
	<%= link_to 'Back', articles_path %>
</div>

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name">
      <strong>
        <%= comment.commenter %>
      </strong>
    </p>

    <p class="comment_body">
      <%= comment.body %>
    </p>

    <p class="comment_time">
      <%= time_ago_in_words(comment.created_at) %> Ago
    </p>

    <p>
    <%= link_to 'Delete', [comment.article, comment],
                 method: :delete,
                 class: "button",
                 data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %><br>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </div>

    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "About Me", about_path %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="https://twitter.com/prasanga_regmi">Twitter</a></li>
      <li><a href="https://github.com/prasanga1">Github</a></li>
      <li><a href="https://www.facebook.com/prasanga.regmi1">Site</a></li>
      <li><a href="mailto:prsregmi@gmail.com">Email</a></li>
    </ul>

    <% if !user_signed_in? %>
      <p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
    <% end %>
  </div>

  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
        <p>All Articles</p>
      <% elsif current_page?(about_path) %>
        <p>About</p>
      <% else %>
        <%= link_to "Back to All Articles", root_path %>
      <% end %>

      <% if  !user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Article", new_article_path %></button>
          <button class="button"><%= link_to "Log out", destroy_user_session_path, method: :delete %></button>
        </div>
      <% end %>
    </div>
    
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="content">
		Hi, my name is Prasanga Regmi. Learning Ruby On Rails.
	</div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<%= link_to 'My Blog', controller: 'articles' %>